# TODO:
# Include: https://github.com/ewels/MultiQC/blob/master/docs/customisation.md

# Project level information
report_header_info:
  - Contact E-mail: "adrian.janucik@gmail.com"
  - Application Type: "RNA-seq for DGE analysis"
  - Project Type: "Application"
  - Sequencing Platform: "Unknown"
  - Sequencing Setup: "Unknown"
  - Protocol: "Assumes TruSeq"

# Used for cleaning sample names. Should be strings.
# NB: These are removed in order!
fn_clean_exts:
  - ".gz"
  - "_R1"
  - "_R2"
  - "_fastp"
  - "_flagstat"
  - "_raw"
  - "Aligned.sortedByCoord.out.bam"
  - "Log.final.out"
  - "_salmon"

# Removes cell and last two digits
extra_fn_clean_exts:
  - type: regex
    pattern: "_cell_WTS_S\\d+$"

# General removal
sample_names_replace_regex: True
sample_names_replace:
  "_T1": ""
  "_L001": ""
  "_1": ""

# For custom order of different reports in the final HTML report
module_order:
  - fastqc:
      path_filters:
        - "*_1_fastqc.zip" # analyse only R1 as R2 is usually artificially worse (due to technical reasons)
  - fastp
  - sortmerna
  - star
  - picard
  - qualimap
  - samtools
  - featureCounts
  - salmon
