# TODO:
# Include: https://github.com/ewels/MultiQC/blob/master/docs/customisation.md

# Project level information
report_header_info:
  - Contact E-mail: "adrian.janucik@gmail.com"
  - Application Type: "RNA-seq for DGE analysis"
  - Project Type: "Application"
  - Sequencing Platform: "Unknown"
  - Sequencing Setup: "Unknown"
  - Protocol: "Assumes TruSeq"

# Used for cleaning sample names. Should be strings.
# NB: These are removed in order!
fn_clean_exts:
  - ".gz"
  - "_R1"
  - "_R2"
  - "_fastp"
  - "_flagstat"
  - "_raw"
  - "Aligned.sortedByCoord.out.bam"
  - "Log.final.out"
  - "_salmon"

# Removes cell and last two digits
extra_fn_clean_exts:
  - type: regex
    pattern: "_cell_WTS_S\\d+$"

# For custom order of different reports in the final HTML report
module_order:
          - fastqc
          - fastp
          - sortmerna
          - star
          - picard
          - qualimap

# Some modules may not be placed in proper order (e.g. using the above method)
# then the following can be assessed to put `featurecounts` -> `Samtools` from the bottom
report_section_order:
  Samtools:
    before: qualimap
  featureCounts:
    before: Samtools
  Salmon:
    before: featureCcounts
  
